package gui;

import static com.lowagie.text.pdf.PdfFileSpecification.url;
import connect.Conexion;
import connect.PassConnect;
import java.awt.Desktop;
import java.awt.Dimension;
import static java.awt.Frame.MAXIMIZED_BOTH;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Toolkit;
import java.beans.PropertyVetoException;
import java.io.File;
import java.io.IOException;
import java.net.URISyntaxException;
import java.net.URL;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import logic.GestionMembresias;
import logic.GestionSocios;
import org.omg.SendingContext.RunTime;

public class frmPrincipal extends javax.swing.JFrame {

    PassConnect pc;
    String users, nombreUsuario;

    /**
     * Creates new form admin
     */
    public frmPrincipal() {
        initComponents();
        ImageIcon icon = new ImageIcon(getClass().getResource("/img/LogoGym.png"));
        this.setIconImage(icon.getImage());
        this.setExtendedState(MAXIMIZED_BOTH);
        pc = new PassConnect("bdgimnasio", "root", "Jp100702");
        users = frmLogin.usuario;
        CargarUsuario();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jSeparator4 = new javax.swing.JSeparator();
        ImageIcon icon = new ImageIcon(getClass().getResource("/img/gym2.jpg"));
        Image image = icon.getImage();
        escritorio = new javax.swing.JDesktopPane() {
            public void paintComponent(Graphics g){
                g.drawImage(image,0,0,getWidth(),getHeight(),this);
            }

        };
        btnSalirSesion = new javax.swing.JButton();
        lblNombreUsuario = new javax.swing.JLabel();
        barraMenu = new javax.swing.JMenuBar();
        mnuArchivo = new javax.swing.JMenu();
        mnuRegistroMembre = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        mnuMembresiaSocio = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnuSocios = new javax.swing.JMenuItem();
        jSeparator8 = new javax.swing.JPopupMenu.Separator();
        mnuRegistroIngreso = new javax.swing.JMenuItem();
        jSeparator9 = new javax.swing.JPopupMenu.Separator();
        jMenu1 = new javax.swing.JMenu();
        mnuReporteMaestroMembresia = new javax.swing.JMenuItem();
        mnuReporteMaestroSocios = new javax.swing.JMenuItem();
        mnuVentana = new javax.swing.JMenu();
        jmnuConsulta = new javax.swing.JMenu();
        mnuBuscarMembresias = new javax.swing.JMenuItem();
        mnuBuscarRegistroIngresos = new javax.swing.JMenuItem();
        mnuBuscarSocios = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        jmnuVista = new javax.swing.JMenu();
        mnuVistaParalelo = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        mnuVistaCascada = new javax.swing.JMenuItem();
        mnuAyuda = new javax.swing.JMenu();
        jmnuAcercaDe = new javax.swing.JMenuItem();
        jSeparator7 = new javax.swing.JPopupMenu.Separator();
        mnuContenido = new javax.swing.JMenuItem();
        mnuSeguridad = new javax.swing.JMenu();
        mnuUsuarios = new javax.swing.JMenuItem();
        mnuSalir = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnSalirSesion.setBackground(new java.awt.Color(255, 255, 255));
        btnSalirSesion.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        btnSalirSesion.setForeground(new java.awt.Color(0, 0, 0));
        btnSalirSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cerrar-sesion.png"))); // NOI18N
        btnSalirSesion.setText("Cerrar sesión");
        btnSalirSesion.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSalirSesion.setBorderPainted(false);
        btnSalirSesion.setContentAreaFilled(false);
        btnSalirSesion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSalirSesion.setIconTextGap(-5);
        btnSalirSesion.setOpaque(true);
        btnSalirSesion.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSalirSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirSesionActionPerformed(evt);
            }
        });

        lblNombreUsuario.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 14)); // NOI18N
        lblNombreUsuario.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblNombreUsuario.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        lblNombreUsuario.setOpaque(true);

        escritorio.setLayer(btnSalirSesion, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio.setLayer(lblNombreUsuario, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(escritorioLayout.createSequentialGroup()
                .addGap(0, 572, Short.MAX_VALUE)
                .addGroup(escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSalirSesion, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblNombreUsuario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, escritorioLayout.createSequentialGroup()
                .addComponent(lblNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 380, Short.MAX_VALUE)
                .addComponent(btnSalirSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        mnuArchivo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/archivos.png"))); // NOI18N
        mnuArchivo.setText("Gestión");
        mnuArchivo.setFont(new java.awt.Font("Elephant", 1, 14)); // NOI18N

        mnuRegistroMembre.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        mnuRegistroMembre.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        mnuRegistroMembre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/tarjeta-de-membresia.png"))); // NOI18N
        mnuRegistroMembre.setText("Registro Membresias");
        mnuRegistroMembre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuRegistroMembreActionPerformed(evt);
            }
        });
        mnuArchivo.add(mnuRegistroMembre);
        mnuArchivo.add(jSeparator2);

        mnuMembresiaSocio.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        mnuMembresiaSocio.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        mnuMembresiaSocio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/document.png"))); // NOI18N
        mnuMembresiaSocio.setText("Membresias de socios");
        mnuMembresiaSocio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuMembresiaSocioActionPerformed(evt);
            }
        });
        mnuArchivo.add(mnuMembresiaSocio);
        mnuArchivo.add(jSeparator1);

        mnuSocios.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        mnuSocios.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        mnuSocios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/muscle.png"))); // NOI18N
        mnuSocios.setText("Registro Socios");
        mnuSocios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSociosActionPerformed(evt);
            }
        });
        mnuArchivo.add(mnuSocios);
        mnuArchivo.add(jSeparator8);

        mnuRegistroIngreso.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        mnuRegistroIngreso.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        mnuRegistroIngreso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/registro.png"))); // NOI18N
        mnuRegistroIngreso.setText("Registro ingreso");
        mnuRegistroIngreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuRegistroIngresoActionPerformed(evt);
            }
        });
        mnuArchivo.add(mnuRegistroIngreso);
        mnuArchivo.add(jSeparator9);

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/content_32x32.png"))); // NOI18N
        jMenu1.setText("Reporte maestro");
        jMenu1.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N

        mnuReporteMaestroMembresia.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        mnuReporteMaestroMembresia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/tarjeta-de-membresia.png"))); // NOI18N
        mnuReporteMaestroMembresia.setText("Membresias");
        mnuReporteMaestroMembresia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuReporteMaestroMembresiaActionPerformed(evt);
            }
        });
        jMenu1.add(mnuReporteMaestroMembresia);

        mnuReporteMaestroSocios.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        mnuReporteMaestroSocios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/muscle.png"))); // NOI18N
        mnuReporteMaestroSocios.setText("Socios");
        mnuReporteMaestroSocios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuReporteMaestroSociosActionPerformed(evt);
            }
        });
        jMenu1.add(mnuReporteMaestroSocios);

        mnuArchivo.add(jMenu1);

        barraMenu.add(mnuArchivo);

        mnuVentana.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/puntos-de-vista.png"))); // NOI18N
        mnuVentana.setText("Ventana ");
        mnuVentana.setFont(new java.awt.Font("Elephant", 1, 14)); // NOI18N

        jmnuConsulta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/busqueda-de-trabajo.png"))); // NOI18N
        jmnuConsulta.setText("Consultas");
        jmnuConsulta.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N

        mnuBuscarMembresias.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnuBuscarMembresias.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        mnuBuscarMembresias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/tarjeta-de-membresia.png"))); // NOI18N
        mnuBuscarMembresias.setText("Membresias");
        mnuBuscarMembresias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuBuscarMembresiasActionPerformed(evt);
            }
        });
        jmnuConsulta.add(mnuBuscarMembresias);

        mnuBuscarRegistroIngresos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnuBuscarRegistroIngresos.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        mnuBuscarRegistroIngresos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/registro.png"))); // NOI18N
        mnuBuscarRegistroIngresos.setText("Registro Ingresos");
        mnuBuscarRegistroIngresos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuBuscarRegistroIngresosActionPerformed(evt);
            }
        });
        jmnuConsulta.add(mnuBuscarRegistroIngresos);

        mnuBuscarSocios.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnuBuscarSocios.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        mnuBuscarSocios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/muscle.png"))); // NOI18N
        mnuBuscarSocios.setText("Socios");
        mnuBuscarSocios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuBuscarSociosActionPerformed(evt);
            }
        });
        jmnuConsulta.add(mnuBuscarSocios);

        mnuVentana.add(jmnuConsulta);
        mnuVentana.add(jSeparator5);

        jmnuVista.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/visto.png"))); // NOI18N
        jmnuVista.setText("Vista ventanas");
        jmnuVista.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N

        mnuVistaParalelo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, 0));
        mnuVistaParalelo.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        mnuVistaParalelo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/paralelas.png"))); // NOI18N
        mnuVistaParalelo.setText("Paralelo");
        mnuVistaParalelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuVistaParaleloActionPerformed(evt);
            }
        });
        jmnuVista.add(mnuVistaParalelo);
        jmnuVista.add(jSeparator6);

        mnuVistaCascada.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, 0));
        mnuVistaCascada.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        mnuVistaCascada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/boton-de-interfaz-de-opcion-de-visualizacion-en-cascada.png"))); // NOI18N
        mnuVistaCascada.setText("Cascada");
        mnuVistaCascada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuVistaCascadaActionPerformed(evt);
            }
        });
        jmnuVista.add(mnuVistaCascada);

        mnuVentana.add(jmnuVista);

        barraMenu.add(mnuVentana);

        mnuAyuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ayuda.png"))); // NOI18N
        mnuAyuda.setText("Ayuda");
        mnuAyuda.setFont(new java.awt.Font("Elephant", 1, 14)); // NOI18N
        mnuAyuda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuAyudaMouseClicked(evt);
            }
        });

        jmnuAcercaDe.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_DOWN_MASK));
        jmnuAcercaDe.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        jmnuAcercaDe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/acerca-de.png"))); // NOI18N
        jmnuAcercaDe.setText("Acerca de...");
        jmnuAcercaDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmnuAcercaDeActionPerformed(evt);
            }
        });
        mnuAyuda.add(jmnuAcercaDe);
        mnuAyuda.add(jSeparator7);

        mnuContenido.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_DOWN_MASK));
        mnuContenido.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        mnuContenido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/gestion-de-contenido.png"))); // NOI18N
        mnuContenido.setText("Contenido");
        mnuContenido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuContenidoMouseClicked(evt);
            }
        });
        mnuContenido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuContenidoActionPerformed(evt);
            }
        });
        mnuAyuda.add(mnuContenido);

        barraMenu.add(mnuAyuda);

        mnuSeguridad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/proteger.png"))); // NOI18N
        mnuSeguridad.setText("Seguridad");
        mnuSeguridad.setFont(new java.awt.Font("Elephant", 1, 14)); // NOI18N

        mnuUsuarios.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        mnuUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/usuario.png"))); // NOI18N
        mnuUsuarios.setText("Usuarios");
        mnuUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuUsuariosActionPerformed(evt);
            }
        });
        mnuSeguridad.add(mnuUsuarios);

        barraMenu.add(mnuSeguridad);

        mnuSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/salida.png"))); // NOI18N
        mnuSalir.setText("Salir");
        mnuSalir.setFont(new java.awt.Font("Elephant", 1, 14)); // NOI18N
        mnuSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuSalirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mnuSalirMouseEntered(evt);
            }
        });
        mnuSalir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                mnuSalirKeyPressed(evt);
            }
        });
        barraMenu.add(mnuSalir);

        setJMenuBar(barraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuRegistroMembreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuRegistroMembreActionPerformed
        frmRegistroMembresias frmRegM = new frmRegistroMembresias();
        escritorio.add(frmRegM);
        frmRegM.show();
    }//GEN-LAST:event_mnuRegistroMembreActionPerformed

    private void mnuSociosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSociosActionPerformed
        frmRegistroSocios frmRegSocios = new frmRegistroSocios();
        escritorio.add(frmRegSocios);
        frmRegSocios.show();
    }//GEN-LAST:event_mnuSociosActionPerformed

    private void mnuMembresiaSocioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuMembresiaSocioActionPerformed
        frmRegistroMembresiaSocios frmMemSoc = new frmRegistroMembresiaSocios();
        escritorio.add(frmMemSoc);
        frmMemSoc.show();
    }//GEN-LAST:event_mnuMembresiaSocioActionPerformed

    private void mnuSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuSalirMouseClicked
        int resp = JOptionPane.showConfirmDialog(null, "¿Desea salir del sistema de control del Gym APJM?", "Salir", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        if (resp == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_mnuSalirMouseClicked

    private void mnuRegistroIngresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuRegistroIngresoActionPerformed
        frmRegistroIngreso frmRegIngreso = new frmRegistroIngreso();
        escritorio.add(frmRegIngreso);
        frmRegIngreso.show();
    }//GEN-LAST:event_mnuRegistroIngresoActionPerformed

    private void mnuBuscarMembresiasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuBuscarMembresiasActionPerformed
        frmBuscarMembresias frmBuscMembre = new frmBuscarMembresias();
        escritorio.add(frmBuscMembre);
        frmBuscMembre.show();
    }//GEN-LAST:event_mnuBuscarMembresiasActionPerformed

    private void mnuBuscarSociosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuBuscarSociosActionPerformed
        frmBuscarSocios frmBuscSocios = new frmBuscarSocios();
        escritorio.add(frmBuscSocios);
        frmBuscSocios.show();
    }//GEN-LAST:event_mnuBuscarSociosActionPerformed

    private void mnuBuscarRegistroIngresosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuBuscarRegistroIngresosActionPerformed
        frmBuscarRegistroIngresos frmscBusRegistroIngreso = new frmBuscarRegistroIngresos();
        escritorio.add(frmscBusRegistroIngreso);
        frmscBusRegistroIngreso.show();
    }//GEN-LAST:event_mnuBuscarRegistroIngresosActionPerformed

    private void mnuAyudaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuAyudaMouseClicked

    }//GEN-LAST:event_mnuAyudaMouseClicked

    private void mnuVistaParaleloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuVistaParaleloActionPerformed
        int x = (int) (Toolkit.getDefaultToolkit().getScreenSize().getWidth());
        int y = (int) (Toolkit.getDefaultToolkit().getScreenSize().getHeight());
        JInternalFrame objetos[] = escritorio.getAllFrames();
        if (objetos.length > 0) {
            int ancho = x / objetos.length;
            int largo = x / objetos.length;
            x = y = 0;
            for (JInternalFrame v : objetos) {
                v.setSize(ancho, largo);
                v.setLocation(x, y);
                x += ancho;
            }
        }
    }//GEN-LAST:event_mnuVistaParaleloActionPerformed

    private void jmnuAcercaDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmnuAcercaDeActionPerformed
        frmAyuda frmAyuda = new frmAyuda();
        escritorio.add(frmAyuda);
        Dimension desktopSize = escritorio.getSize();
        Dimension FrameSize = frmAyuda.getSize();
        frmAyuda.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
        frmAyuda.show();
    }//GEN-LAST:event_jmnuAcercaDeActionPerformed

    private void mnuSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuSalirMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuSalirMouseEntered

    private void mnuSalirKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mnuSalirKeyPressed

    }//GEN-LAST:event_mnuSalirKeyPressed

    private void btnSalirSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirSesionActionPerformed
        int resp = JOptionPane.showConfirmDialog(null, "¿Seguro que desea cerrar sesión?", "Salir", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        if (resp == JOptionPane.YES_OPTION) {
            try {
                frmLogin log = new frmLogin();
                log.setVisible(true);
                this.dispose();
            } catch (SQLException ex) {
                Logger.getLogger(frmPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_btnSalirSesionActionPerformed

    private void mnuVistaCascadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuVistaCascadaActionPerformed
        int xOffset = 30, yOffset = 30;
        JInternalFrame objetos[] = escritorio.getAllFrames();
        for (JInternalFrame v : objetos) {
            v.setLocation(xOffset += 25, yOffset += 30);
            try {
                v.setSelected(true);
            } catch (PropertyVetoException ex) {
                Logger.getLogger(frmPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_mnuVistaCascadaActionPerformed

    private void mnuContenidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuContenidoActionPerformed
//URL in = this.getClass().getResource("/manual/EIF204 - PROGRAMACIÓN II - IC2022 Firmado.pdf");    

        // String url = "C:\\Users\\jpesp\\OneDrive\\Documents\\Ingenieria en Sistemas\\Programacion 2\\Proyectos\\appGimnasio\\src\\manual\\EIF204 - PROGRAMACIÓN II - IC2022 Firmado.pdf";
//        ProcessBuilder p = new ProcessBuilder();
//        p.command("cmd.exe","/C", url);
//        try {
//            p.start();
//        } catch (IOException ex) {
//            Logger.getLogger(frmPrincipal.class.getName()).log(Level.SEVERE, null, ex);
//        }
//File path = new File("/manual/EIF204 - PROGRAMACIÓN II - IC2022 Firmado.pdf");
        URL pathc = this.getClass().getResource("/manual/Manual_de_Usuario_GYM_APJM.pdf");
        try {
            Desktop.getDesktop().open(new File(pathc.toURI()));
        } catch (IOException | URISyntaxException ex) {
            Logger.getLogger(frmPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_mnuContenidoActionPerformed

    private void mnuContenidoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuContenidoMouseClicked

    }//GEN-LAST:event_mnuContenidoMouseClicked

    private void mnuReporteMaestroSociosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuReporteMaestroSociosActionPerformed
        GestionSocios gestionSocios = new GestionSocios();
        gestionSocios.cargarReporteMaestroSocios();
    }//GEN-LAST:event_mnuReporteMaestroSociosActionPerformed

    private void mnuReporteMaestroMembresiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuReporteMaestroMembresiaActionPerformed
        GestionMembresias gestionMembresia = new GestionMembresias();
        gestionMembresia.cargarReporteMaestroMembresia();
    }//GEN-LAST:event_mnuReporteMaestroMembresiaActionPerformed

    private void mnuUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuUsuariosActionPerformed

        frmRegistroUsuarios frmReg = null;
        try {
            frmReg = new frmRegistroUsuarios();
        } catch (SQLException ex) {
            Logger.getLogger(frmPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }

        frmReg.setVisible(true);
        frmReg.setLocationRelativeTo(escritorio);


    }//GEN-LAST:event_mnuUsuariosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPrincipal().setVisible(true);
            }
        });
    }

    public void abrirPDF(String ruta) {
        try {
            File file = new File(ruta);
            Desktop.getDesktop().open(file);
        } catch (IOException ex) {
            Logger.getLogger(frmPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    public void CargarUsuario() {
        Conexion con = new Conexion();
        con.conectarBD();

        try {
            //llamado de la clase conexion con el metodo db que contiene la conexion de a  la db

            PreparedStatement pst = con.getConexion().prepareStatement(
                    "Select nombre from tblusers where users = '" + users + "'");

            ResultSet rs = pst.executeQuery();

            if (rs.next()) {
                nombreUsuario = rs.getString("nombre");
                lblNombreUsuario.setText("Usuario: " + nombreUsuario);
//                    jMenu1.setText("Sesión de " + users);
            }

        } catch (SQLException e) {
            System.err.println("Error en conexion desde la interfaz administrador ");
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JMenuBar barraMenu;
    public javax.swing.JButton btnSalirSesion;
    public javax.swing.JDesktopPane escritorio;
    public javax.swing.JMenu jMenu1;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JPopupMenu.Separator jSeparator1;
    public javax.swing.JPopupMenu.Separator jSeparator2;
    public javax.swing.JSeparator jSeparator4;
    public javax.swing.JPopupMenu.Separator jSeparator5;
    public javax.swing.JPopupMenu.Separator jSeparator6;
    public javax.swing.JPopupMenu.Separator jSeparator7;
    public javax.swing.JPopupMenu.Separator jSeparator8;
    public javax.swing.JPopupMenu.Separator jSeparator9;
    public javax.swing.JMenuItem jmnuAcercaDe;
    public javax.swing.JMenu jmnuConsulta;
    public javax.swing.JMenu jmnuVista;
    public javax.swing.JLabel lblNombreUsuario;
    public javax.swing.JMenu mnuArchivo;
    public javax.swing.JMenu mnuAyuda;
    public javax.swing.JMenuItem mnuBuscarMembresias;
    public javax.swing.JMenuItem mnuBuscarRegistroIngresos;
    public javax.swing.JMenuItem mnuBuscarSocios;
    public javax.swing.JMenuItem mnuContenido;
    public static javax.swing.JMenuItem mnuMembresiaSocio;
    public static javax.swing.JMenuItem mnuRegistroIngreso;
    public static javax.swing.JMenuItem mnuRegistroMembre;
    public javax.swing.JMenuItem mnuReporteMaestroMembresia;
    public javax.swing.JMenuItem mnuReporteMaestroSocios;
    public javax.swing.JMenu mnuSalir;
    public static javax.swing.JMenu mnuSeguridad;
    public static javax.swing.JMenuItem mnuSocios;
    public javax.swing.JMenuItem mnuUsuarios;
    public javax.swing.JMenu mnuVentana;
    public javax.swing.JMenuItem mnuVistaCascada;
    public javax.swing.JMenuItem mnuVistaParalelo;
    // End of variables declaration//GEN-END:variables
}
