/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.Graphics;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.nio.channels.FileChannel;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import logic.GestionSocios;
import logic.Socios;

public class frmRegistroSocios extends javax.swing.JInternalFrame {

    GestionSocios gestionSocios;
    Socios socios;

    public frmRegistroSocios() {
        initComponents();
        gestionSocios = new GestionSocios();
        socios = null;
        listarSocios();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        winRegSocios = new javax.swing.JDialog();
        ImageIcon icon = new ImageIcon(getClass().getResource("/img/fondo2.jpg"));
        Image image = icon.getImage();
        jPanel1 =  new javax.swing.JPanel()
        {
            public void paintComponent(Graphics g){
                g.drawImage(image,0,0,getWidth(),getHeight(),this);
            }}

            ;
            jPanel2 = new javax.swing.JPanel();
            jLabel5 = new javax.swing.JLabel();
            jLabel7 = new javax.swing.JLabel();
            txtIdSocio = new javax.swing.JTextField();
            txtNombre = new javax.swing.JTextField();
            txtPrimerApe = new javax.swing.JTextField();
            txtSegundoApe = new javax.swing.JTextField();
            jLabel1 = new javax.swing.JLabel();
            txtTelefonoMovil = new javax.swing.JTextField();
            jLabel2 = new javax.swing.JLabel();
            txtTelefonoFijo = new javax.swing.JTextField();
            jLabel3 = new javax.swing.JLabel();
            txtCorreo = new javax.swing.JTextField();
            jLabel4 = new javax.swing.JLabel();
            jLabel6 = new javax.swing.JLabel();
            fotoSocio = new jcFoto.jcFoto();
            btnGuardarFoto = new javax.swing.JButton();
            btnSave = new javax.swing.JButton();
            btnCancelar = new javax.swing.JButton();
            PopUpmnuSocios = new javax.swing.JPopupMenu();
            popMnuEditar = new javax.swing.JMenuItem();
            popMnuEliminar = new javax.swing.JMenuItem();
            popMnuImprimir = new javax.swing.JMenuItem();
            jSeparator1 = new javax.swing.JPopupMenu.Separator();
            popMnuSalir = new javax.swing.JMenuItem();
            jPanel3 = new javax.swing.JPanel();
            Herramientas = new javax.swing.JToolBar();
            btnGuardar = new javax.swing.JButton();
            btnEditar = new javax.swing.JButton();
            btnEliminar = new javax.swing.JButton();
            btnImprimir = new javax.swing.JButton();
            btnClose = new javax.swing.JButton();
            jScrollPane1 = new javax.swing.JScrollPane();
            tblSocios = new javax.swing.JTable();
            lbTotal = new javax.swing.JLabel();

            jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Registro Socios", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Leelawadee UI Semilight", 1, 14))); // NOI18N

            jPanel2.setBackground(new java.awt.Color(123, 113, 108));
            jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
            jPanel2.setForeground(new java.awt.Color(135, 107, 93));
            jPanel2.setDoubleBuffered(false);
            jPanel2.setFocusable(false);

            jLabel5.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
            jLabel5.setText("Telefono movil:");
            jLabel5.setFocusable(false);

            jLabel7.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
            jLabel7.setText("Correo: ");
            jLabel7.setFocusable(false);

            txtIdSocio.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
            txtIdSocio.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    txtIdSocioActionPerformed(evt);
                }
            });
            txtIdSocio.addKeyListener(new java.awt.event.KeyAdapter() {
                public void keyPressed(java.awt.event.KeyEvent evt) {
                    txtIdSocioKeyPressed(evt);
                }
            });

            txtNombre.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
            txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
                public void keyPressed(java.awt.event.KeyEvent evt) {
                    txtNombreKeyPressed(evt);
                }
            });

            txtPrimerApe.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
            txtPrimerApe.addKeyListener(new java.awt.event.KeyAdapter() {
                public void keyPressed(java.awt.event.KeyEvent evt) {
                    txtPrimerApeKeyPressed(evt);
                }
            });

            txtSegundoApe.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
            txtSegundoApe.addKeyListener(new java.awt.event.KeyAdapter() {
                public void keyPressed(java.awt.event.KeyEvent evt) {
                    txtSegundoApeKeyPressed(evt);
                }
            });

            jLabel1.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
            jLabel1.setText("ID Socio:");
            jLabel1.setFocusable(false);

            txtTelefonoMovil.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
            txtTelefonoMovil.addKeyListener(new java.awt.event.KeyAdapter() {
                public void keyPressed(java.awt.event.KeyEvent evt) {
                    txtTelefonoMovilKeyPressed(evt);
                }
            });

            jLabel2.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
            jLabel2.setText("Nombre:");
            jLabel2.setFocusable(false);

            txtTelefonoFijo.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
            txtTelefonoFijo.addKeyListener(new java.awt.event.KeyAdapter() {
                public void keyPressed(java.awt.event.KeyEvent evt) {
                    txtTelefonoFijoKeyPressed(evt);
                }
            });

            jLabel3.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
            jLabel3.setText("Primer Apellido:");
            jLabel3.setFocusable(false);

            txtCorreo.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
            txtCorreo.addKeyListener(new java.awt.event.KeyAdapter() {
                public void keyPressed(java.awt.event.KeyEvent evt) {
                    txtCorreoKeyPressed(evt);
                }
            });

            jLabel4.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
            jLabel4.setText("Segundo Apellido:");
            jLabel4.setFocusable(false);

            jLabel6.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
            jLabel6.setText("Telefono fijo:");
            jLabel6.setFocusable(false);

            javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
            jPanel2.setLayout(jPanel2Layout);
            jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(6, 6, 6)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtIdSocio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                        .addComponent(txtNombre, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(txtPrimerApe, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(txtSegundoApe, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtTelefonoMovil, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
                            .addComponent(txtCorreo, javax.swing.GroupLayout.Alignment.LEADING))
                        .addComponent(txtTelefonoFijo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(37, 37, 37))
            );
            jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(txtTelefonoFijo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(txtIdSocio, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(0, 3, Short.MAX_VALUE))
                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3)
                                .addComponent(txtPrimerApe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel4)
                                .addComponent(txtSegundoApe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtTelefonoMovil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addContainerGap())
            );

            btnGuardarFoto.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
            btnGuardarFoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/tarjeta-de-membresia.png"))); // NOI18N
            btnGuardarFoto.setText("Guardar foto");
            btnGuardarFoto.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnGuardarFotoActionPerformed(evt);
                }
            });

            btnSave.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
            btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/agregar-archivo.png"))); // NOI18N
            btnSave.setText("Guardar");
            btnSave.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnSaveActionPerformed(evt);
                }
            });

            btnCancelar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
            btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/eliminar.png"))); // NOI18N
            btnCancelar.setText("Cancelar");
            btnCancelar.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnCancelarActionPerformed(evt);
                }
            });

            javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
            jPanel1.setLayout(jPanel1Layout);
            jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(fotoSocio, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(301, 301, 301)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btnCancelar)
                                        .addComponent(btnSave)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(btnGuardarFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            );
            jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(27, 27, 27)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnCancelar))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnGuardarFoto)
                            .addComponent(fotoSocio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(57, Short.MAX_VALUE))
            );

            javax.swing.GroupLayout winRegSociosLayout = new javax.swing.GroupLayout(winRegSocios.getContentPane());
            winRegSocios.getContentPane().setLayout(winRegSociosLayout);
            winRegSociosLayout.setHorizontalGroup(
                winRegSociosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            );
            winRegSociosLayout.setVerticalGroup(
                winRegSociosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            );

            popMnuEditar.setText("Editar");
            popMnuEditar.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    popMnuEditarActionPerformed(evt);
                }
            });
            PopUpmnuSocios.add(popMnuEditar);

            popMnuEliminar.setText("Eliminar");
            popMnuEliminar.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    popMnuEliminarActionPerformed(evt);
                }
            });
            PopUpmnuSocios.add(popMnuEliminar);

            popMnuImprimir.setText("Imprimir");
            popMnuImprimir.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    popMnuImprimirActionPerformed(evt);
                }
            });
            PopUpmnuSocios.add(popMnuImprimir);
            PopUpmnuSocios.add(jSeparator1);

            popMnuSalir.setText("Salir");
            popMnuSalir.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    popMnuSalirActionPerformed(evt);
                }
            });
            PopUpmnuSocios.add(popMnuSalir);

            setClosable(true);
            setIconifiable(true);
            setMaximizable(true);
            setResizable(true);
            setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/img/muscle.png"))); // NOI18N
            setPreferredSize(new java.awt.Dimension(900, 500));

            jPanel3.setBackground(new java.awt.Color(130, 114, 103));

            Herramientas.setBackground(new java.awt.Color(135, 107, 93));
            Herramientas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
            Herramientas.setForeground(new java.awt.Color(135, 107, 93));
            Herramientas.setRollover(true);

            btnGuardar.setFont(new java.awt.Font("Microsoft YaHei", 1, 14)); // NOI18N
            btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/dumbbell.png"))); // NOI18N
            btnGuardar.setText("Guardar");
            btnGuardar.setFocusable(false);
            btnGuardar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
            btnGuardar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
            btnGuardar.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnGuardarActionPerformed(evt);
                }
            });
            Herramientas.add(btnGuardar);

            btnEditar.setFont(new java.awt.Font("Microsoft YaHei", 1, 14)); // NOI18N
            btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/muscle2.png"))); // NOI18N
            btnEditar.setText("Editar");
            btnEditar.setFocusable(false);
            btnEditar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
            btnEditar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
            btnEditar.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnEditarActionPerformed(evt);
                }
            });
            Herramientas.add(btnEditar);

            btnEliminar.setFont(new java.awt.Font("Microsoft YaHei", 1, 14)); // NOI18N
            btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/eliminargym.png"))); // NOI18N
            btnEliminar.setText("Eliminar");
            btnEliminar.setFocusable(false);
            btnEliminar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
            btnEliminar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
            btnEliminar.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnEliminarActionPerformed(evt);
                }
            });
            Herramientas.add(btnEliminar);

            btnImprimir.setFont(new java.awt.Font("Microsoft YaHei", 1, 14)); // NOI18N
            btnImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/impresora.png"))); // NOI18N
            btnImprimir.setText("Imprimir");
            btnImprimir.setFocusable(false);
            btnImprimir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
            btnImprimir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
            btnImprimir.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnImprimirActionPerformed(evt);
                }
            });
            Herramientas.add(btnImprimir);

            btnClose.setFont(new java.awt.Font("Microsoft YaHei", 1, 14)); // NOI18N
            btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/salida.png"))); // NOI18N
            btnClose.setText("Salir");
            btnClose.setFocusable(false);
            btnClose.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
            btnClose.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
            btnClose.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnCloseActionPerformed(evt);
                }
            });
            Herramientas.add(btnClose);

            jScrollPane1.setComponentPopupMenu(PopUpmnuSocios);
            jScrollPane1.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 12)); // NOI18N

            tblSocios.setAutoCreateRowSorter(true);
            tblSocios.setBackground(new java.awt.Color(189, 175, 145));
            tblSocios.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
            tblSocios.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {

                },
                new String [] {
                    "ID Socio", "Nombre", "Primer Apellido", "Segundo Apellido", "Telefono Movil", "Telefono Fijo", "Correo"
                }
            ));
            tblSocios.setComponentPopupMenu(PopUpmnuSocios);
            tblSocios.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    tblSociosMouseClicked(evt);
                }
            });
            jScrollPane1.setViewportView(tblSocios);

            lbTotal.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
            lbTotal.setText("Total:");

            javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
            jPanel3.setLayout(jPanel3Layout);
            jPanel3Layout.setHorizontalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(lbTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Herramientas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 892, Short.MAX_VALUE))
                    .addContainerGap())
            );
            jPanel3Layout.setVerticalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(Herramientas, javax.swing.GroupLayout.PREFERRED_SIZE, 54, Short.MAX_VALUE)
                    .addGap(28, 28, 28)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(lbTotal)
                    .addGap(77, 77, 77))
            );

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 0, 0)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            );

            pack();
        }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        winRegSocios.setSize(900, 510);
        winRegSocios.setTitle("Guardar");
        ImageIcon img = new ImageIcon(getClass().getResource("/img/registro.png"));
        winRegSocios.setIconImage(img.getImage());
        limpiar();
        winRegSocios.setLocationRelativeTo(winRegSocios);
        winRegSocios.setVisible(true);
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        int fila = tblSocios.getSelectedRow();
        if (fila != -1) {

            winRegSocios.setSize(900, 510);
            winRegSocios.setTitle("Editar");
            ImageIcon icon = new ImageIcon(getClass().getResource("/img/registro.png"));
            winRegSocios.setIconImage(icon.getImage());
            int idSocio = Integer.parseInt(tblSocios.getValueAt(fila, 0).toString());
            socios = gestionSocios.buscarSocio(idSocio);
            txtIdSocio.setEditable(false);
            txtIdSocio.setText(String.valueOf(socios.getIdSocio()));
            txtNombre.setText(socios.getNombre());
            txtPrimerApe.setText(socios.getPrimerApe());
            txtSegundoApe.setText(socios.getSegundoApe());
            txtTelefonoFijo.setText(socios.getTelefonoFijo());
            txtTelefonoMovil.setText(socios.getTelefonoMovil());
            txtCorreo.setText(socios.getCorreo());
            winRegSocios.setLocationRelativeTo(winRegSocios);
            winRegSocios.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(rootPane, "Seleccione el socio que desea editar", "Editar", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        int fila = tblSocios.getSelectedRow();
        if (fila != -1) {
            int idSocio = Integer.parseInt(tblSocios.getValueAt(fila, 0).toString());
            int resp = JOptionPane.showConfirmDialog(rootPane, "¿Esta seguro de eliminar el socio?" + idSocio, "Eliminar", JOptionPane.YES_OPTION);
            if (resp == JOptionPane.YES_OPTION) {
                gestionSocios.conectarBD();
                if (gestionSocios.eliminarSocio(idSocio)) {
                    JOptionPane.showMessageDialog(rootPane, "Socio eliminado exitosamente", "Eliminar", JOptionPane.INFORMATION_MESSAGE);
                    listarSocios();

                } else {
                    JOptionPane.showMessageDialog(rootPane, "Error al intentar eliminar", "Eliminar", JOptionPane.INFORMATION_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(rootPane, "Seleccione el socio que desea eliminar", "Eliminar", JOptionPane.INFORMATION_MESSAGE);
            }

        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirActionPerformed

        gestionSocios.cargarReporteSocios();
    }//GEN-LAST:event_btnImprimirActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    private void tblSociosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSociosMouseClicked
        if (evt.getClickCount() == 2) { //Al dar doble click
            btnEditarActionPerformed(new ActionEvent(tblSocios, 0, ""));
        }
    }//GEN-LAST:event_tblSociosMouseClicked

    private void popMnuEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_popMnuEditarActionPerformed
        btnEditarActionPerformed(evt);
    }//GEN-LAST:event_popMnuEditarActionPerformed

    private void popMnuEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_popMnuEliminarActionPerformed
        btnEliminarActionPerformed(evt);
    }//GEN-LAST:event_popMnuEliminarActionPerformed

    private void popMnuImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_popMnuImprimirActionPerformed
        int fila = tblSocios.getSelectedRow();
        if (fila != -1) {
            int idSocio = Integer.parseInt(tblSocios.getValueAt(fila, 0).toString());
            int resp = JOptionPane.showConfirmDialog(rootPane, "¿Desea imprimir este socio: " + idSocio +"?", "Imprimir", JOptionPane.YES_OPTION);
            if (resp == JOptionPane.YES_OPTION) {
                gestionSocios.cargarReporteUnSocio(idSocio);
            } else {
                JOptionPane.showMessageDialog(rootPane, "Error al intentar imprimir", "Imprimir", JOptionPane.INFORMATION_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Seleccione el socio que desea imprimir", "imprimir", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_popMnuImprimirActionPerformed

    private void popMnuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_popMnuSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_popMnuSalirActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        winRegSocios.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed

        String msg = validarDatos();
        if (msg.equals("")) {
            socios = new Socios();
            socios.setIdSocio(Integer.parseInt(txtIdSocio.getText()));
            socios.setNombre(txtNombre.getText());
            socios.setPrimerApe(txtPrimerApe.getText());
            socios.setSegundoApe(txtSegundoApe.getText());
            socios.setTelefonoMovil(txtTelefonoMovil.getText());
            socios.setTelefonoFijo(txtTelefonoFijo.getText());
            socios.setCorreo(txtCorreo.getText());

            if (winRegSocios.getTitle().equals("Guardar")) {
                if (gestionSocios.insertarSocios(socios)) {
                    JOptionPane.showMessageDialog(winRegSocios, "Socio almacenado exitosamente", "Guardar", JOptionPane.INFORMATION_MESSAGE);
                    winRegSocios.dispose();
                    listarSocios();

                } else {
                    JOptionPane.showMessageDialog(winRegSocios, "Error al intentar guardar socio", "Guardar", JOptionPane.ERROR_MESSAGE);
                }
            }
            if (winRegSocios.getTitle().equals("Editar")) {
                if (gestionSocios.editarSocios(socios)) {
                    JOptionPane.showMessageDialog(winRegSocios, "Socio editado exitosamente", "Editar", JOptionPane.INFORMATION_MESSAGE);
                    winRegSocios.dispose();
                    listarSocios();
                } else {
                    JOptionPane.showMessageDialog(winRegSocios, "Error al intentar editar el Socio", "Editar", JOptionPane.ERROR_MESSAGE);
                }

            }

        } else {
            JOptionPane.showMessageDialog(winRegSocios, msg, "Validando datos", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnGuardarFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarFotoActionPerformed
        if (fotoSocio.getPathFoto() != null
                && guardarFoto(Integer.parseInt(txtIdSocio.getText()))) {
            JOptionPane.showMessageDialog(rootPane, "Fotografia almacenada exitosamente", "Guardar",
                    JOptionPane.INFORMATION_MESSAGE);

        } else {
            JOptionPane.showMessageDialog(rootPane, "No incluye fotografía", "Guardar",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnGuardarFotoActionPerformed

    private void txtIdSocioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdSocioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdSocioActionPerformed

    private void txtIdSocioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdSocioKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (txtIdSocio.getText().trim().equals("")) {
                JOptionPane.showMessageDialog(null, "Por favor ingrese un id");
                txtIdSocio.requestFocus();

            } else {
                btnSave.doClick();
            }
        }
    }//GEN-LAST:event_txtIdSocioKeyPressed

    private void txtNombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (txtNombre.getText().trim().equals("")) {
                JOptionPane.showMessageDialog(null, "Por favor ingrese un nombre");
                txtNombre.requestFocus();

            } else {
                btnSave.doClick();
            }
        }
    }//GEN-LAST:event_txtNombreKeyPressed

    private void txtPrimerApeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrimerApeKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (txtPrimerApe.getText().trim().equals("")) {
                JOptionPane.showMessageDialog(null, "Por favor ingrese un apellido");
                txtPrimerApe.requestFocus();

            } else {
                btnSave.doClick();
            }
        }
    }//GEN-LAST:event_txtPrimerApeKeyPressed

    private void txtSegundoApeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSegundoApeKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (txtSegundoApe.getText().trim().equals("")) {
                JOptionPane.showMessageDialog(null, "Por favor ingrese un apellido");
                txtSegundoApe.requestFocus();

            } else {
                btnSave.doClick();
            }
        }
    }//GEN-LAST:event_txtSegundoApeKeyPressed

    private void txtTelefonoFijoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonoFijoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (txtTelefonoFijo.getText().trim().equals("")) {
                JOptionPane.showMessageDialog(null, "Por favor ingrese un # telefónico");
                txtTelefonoFijo.requestFocus();

            } else {
                btnSave.doClick();
            }
        }
    }//GEN-LAST:event_txtTelefonoFijoKeyPressed

    private void txtTelefonoMovilKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonoMovilKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (txtTelefonoMovil.getText().trim().equals("")) {
                JOptionPane.showMessageDialog(null, "Por favor ingrese un # telefónico");
                txtTelefonoMovil.requestFocus();

            } else {
                btnSave.doClick();
            }
        }
    }//GEN-LAST:event_txtTelefonoMovilKeyPressed

    private void txtCorreoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCorreoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (txtCorreo.getText().trim().equals("")) {
                JOptionPane.showMessageDialog(null, "Por favor ingrese un correo electrónico");
                txtCorreo.requestFocus();

            } else {
                btnSave.doClick();
            }
        }
    }//GEN-LAST:event_txtCorreoKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JToolBar Herramientas;
    public static javax.swing.JPopupMenu PopUpmnuSocios;
    public static javax.swing.JButton btnCancelar;
    public static javax.swing.JButton btnClose;
    public static javax.swing.JButton btnEditar;
    public static javax.swing.JButton btnEliminar;
    public static javax.swing.JButton btnGuardar;
    public static javax.swing.JButton btnGuardarFoto;
    public static javax.swing.JButton btnImprimir;
    public static javax.swing.JButton btnSave;
    public static jcFoto.jcFoto fotoSocio;
    public static javax.swing.JLabel jLabel1;
    public static javax.swing.JLabel jLabel2;
    public static javax.swing.JLabel jLabel3;
    public static javax.swing.JLabel jLabel4;
    public static javax.swing.JLabel jLabel5;
    public static javax.swing.JLabel jLabel6;
    public static javax.swing.JLabel jLabel7;
    public static javax.swing.JPanel jPanel1;
    public static javax.swing.JPanel jPanel2;
    public static javax.swing.JPanel jPanel3;
    public static javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JPopupMenu.Separator jSeparator1;
    public static javax.swing.JLabel lbTotal;
    public static javax.swing.JMenuItem popMnuEditar;
    public static javax.swing.JMenuItem popMnuEliminar;
    public static javax.swing.JMenuItem popMnuImprimir;
    public static javax.swing.JMenuItem popMnuSalir;
    public static javax.swing.JTable tblSocios;
    public static javax.swing.JTextField txtCorreo;
    public static javax.swing.JTextField txtIdSocio;
    public static javax.swing.JTextField txtNombre;
    public static javax.swing.JTextField txtPrimerApe;
    public static javax.swing.JTextField txtSegundoApe;
    public static javax.swing.JTextField txtTelefonoFijo;
    public static javax.swing.JTextField txtTelefonoMovil;
    public static javax.swing.JDialog winRegSocios;
    // End of variables declaration//GEN-END:variables

    private void listarSocios() {
        gestionSocios.conectarBD();
        ResultSet rs = gestionSocios.listarSocios();
        if (rs != null) {
            tblSocios.setModel(gestionSocios.cargarEnTabla(rs));
            lbTotal.setText("Total: " + tblSocios.getRowCount());
        }
        gestionSocios.desconectarBD();
    }

    private String validarDatos() {
        if (txtIdSocio.getText().trim().equals("")) {
            txtIdSocio.requestFocus();
            return "Por favor ingrese el id del Socio";
        } else {
            try {
                Integer.parseInt(txtIdSocio.getText());
            } catch (NumberFormatException e) {
                txtIdSocio.requestFocus();
                return "El Id tiene que ser en formato de numero";
            }
        }

        if (txtNombre.getText().trim().equals("")) {
            txtNombre.requestFocus();
            return "Por favor ingrese el nombre del socio";
        }

        if (txtPrimerApe.getText().trim().equals("")) {
            txtPrimerApe.requestFocus();
            return "Por favor ingrese el primer apellido";
        }
        if (txtSegundoApe.getText().trim().equals("")) {
            txtSegundoApe.requestFocus();
            return "Por favor ingrese el segundo apellido";
        }
        if (txtTelefonoMovil.getText().trim().equals("")) {
            txtTelefonoMovil.requestFocus();
            return "Por favor ingrese el telefono movil";
        }
        if (txtTelefonoFijo.getText().trim().equals("")) {
            txtTelefonoFijo.requestFocus();
            return "Por favor ingrese el telefono fijo";
        }
        if (txtCorreo.getText().trim().equals("")) {
            txtCorreo.requestFocus();
            return "Por favor ingrese el correo";
        }
        return "";
    }

    private boolean guardarFoto(int id) {
        int dotPos = fotoSocio.getPathFoto().lastIndexOf(".");
        String extension = fotoSocio.getPathFoto().substring(dotPos);
        String dir = System.getProperty("user.dir") + "\\"
                + id + extension;
        File entrada = new File(fotoSocio.getPathFoto());
        File salida = new File(dir);
        boolean resp = copyFile(entrada, salida) ? true : false;
        return resp;
    }

    public boolean copyFile(File entrada, File salida) {
        try {
            FileChannel out;
            try (FileChannel in = (new FileInputStream(entrada)).getChannel()) {
                out = (new FileOutputStream(salida)).getChannel();
                in.transferTo(0, entrada.length(), out);
            }
            out.close();
            return true;
        } catch (IOException e) {
            return false;
        }
    }

    private void limpiar() {
        txtIdSocio.setText("");
        txtNombre.setText("");
        txtPrimerApe.setText("");
        txtSegundoApe.setText("");
        txtTelefonoMovil.setText("");
        txtTelefonoFijo.setText("");
        txtCorreo.setText("");
    }
}
