/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.Graphics;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import logic.GestionMembresias;
import logic.Membresias;

public class frmRegistroMembresias extends javax.swing.JInternalFrame {

    GestionMembresias gestionMembresias;
    Membresias membresias;

    public frmRegistroMembresias() {
        initComponents();
        gestionMembresias = new GestionMembresias();
        membresias = null;
        listarMembresias();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        winRegistroMembresias = new javax.swing.JDialog();
        ImageIcon icon = new ImageIcon(getClass().getResource("/img/fondo2.jpg"));
        Image image = icon.getImage();
        jPanel1 = new javax.swing.JPanel() {
            public void paintComponent(Graphics g){
                g.drawImage(image,0,0,getWidth(),getHeight(),this);
            }}
            ;
            jPanel2 = new javax.swing.JPanel();
            txtDescripcion = new javax.swing.JTextField();
            cmbPeriodo = new javax.swing.JComboBox<>();
            txtPrecio = new javax.swing.JTextField();
            jLabel5 = new javax.swing.JLabel();
            jLabel6 = new javax.swing.JLabel();
            jLabel1 = new javax.swing.JLabel();
            jLabel2 = new javax.swing.JLabel();
            jLabel3 = new javax.swing.JLabel();
            jLabel4 = new javax.swing.JLabel();
            txtIdMembresia = new javax.swing.JTextField();
            txtNombre = new javax.swing.JTextField();
            btnSave = new javax.swing.JButton();
            btnCancel = new javax.swing.JButton();
            PopUpmnuMembresia = new javax.swing.JPopupMenu();
            popMnuEditar = new javax.swing.JMenuItem();
            popMnuEliminar = new javax.swing.JMenuItem();
            popMnuImprimir = new javax.swing.JMenuItem();
            jSeparator1 = new javax.swing.JPopupMenu.Separator();
            popMnuCerrar = new javax.swing.JMenuItem();
            jPanel4 = new javax.swing.JPanel();
            lbTotal = new javax.swing.JLabel();
            jScrollPane1 = new javax.swing.JScrollPane();
            tblMembresias = new javax.swing.JTable();
            Herramientas = new javax.swing.JToolBar();
            btnGuardar = new javax.swing.JButton();
            btnEditar = new javax.swing.JButton();
            btnEliminar = new javax.swing.JButton();
            btnImprimir = new javax.swing.JButton();
            btnSalir = new javax.swing.JButton();

            jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos Membresias", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Leelawadee UI Semilight", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N

            jPanel2.setBackground(new java.awt.Color(123, 113, 108));
            jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
            jPanel2.setForeground(new java.awt.Color(255, 255, 255));

            txtDescripcion.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
            txtDescripcion.addKeyListener(new java.awt.event.KeyAdapter() {
                public void keyPressed(java.awt.event.KeyEvent evt) {
                    txtDescripcionKeyPressed(evt);
                }
            });

            cmbPeriodo.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
            cmbPeriodo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una opción", "Dia", "Semana", "Mes", "Bimensual", "Trimestral", "Semestral", "Anual" }));

            txtPrecio.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
            txtPrecio.addKeyListener(new java.awt.event.KeyAdapter() {
                public void keyPressed(java.awt.event.KeyEvent evt) {
                    txtPrecioKeyPressed(evt);
                }
            });

            jLabel5.setBackground(new java.awt.Color(255, 255, 255));
            jLabel5.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
            jLabel5.setForeground(new java.awt.Color(0, 0, 0));
            jLabel5.setText("Periodo de membresia:");
            jLabel5.setFocusable(false);
            jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

            jLabel6.setBackground(new java.awt.Color(255, 255, 255));
            jLabel6.setFont(new java.awt.Font("Microsoft YaHei UI Light", 2, 12)); // NOI18N
            jLabel6.setForeground(new java.awt.Color(0, 0, 0));
            jLabel6.setText("Nota: Dependiendo del tipo de periodo su precio cambia");
            jLabel6.setFocusable(false);
            jLabel6.setOpaque(true);

            jLabel1.setBackground(new java.awt.Color(255, 255, 255));
            jLabel1.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
            jLabel1.setForeground(new java.awt.Color(0, 0, 0));
            jLabel1.setText("ID Membresia:");
            jLabel1.setToolTipText("");
            jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
            jLabel1.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
            jLabel1.setFocusable(false);
            jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

            jLabel2.setBackground(new java.awt.Color(255, 255, 255));
            jLabel2.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
            jLabel2.setForeground(new java.awt.Color(0, 0, 0));
            jLabel2.setText("Nombre:");
            jLabel2.setFocusable(false);
            jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

            jLabel3.setBackground(new java.awt.Color(255, 255, 255));
            jLabel3.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
            jLabel3.setForeground(new java.awt.Color(0, 0, 0));
            jLabel3.setText("Descripcion:");
            jLabel3.setFocusable(false);
            jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

            jLabel4.setBackground(new java.awt.Color(255, 255, 255));
            jLabel4.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
            jLabel4.setForeground(new java.awt.Color(0, 0, 0));
            jLabel4.setText("Precio:");
            jLabel4.setFocusable(false);
            jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

            txtIdMembresia.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
            txtIdMembresia.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    txtIdMembresiaActionPerformed(evt);
                }
            });
            txtIdMembresia.addKeyListener(new java.awt.event.KeyAdapter() {
                public void keyPressed(java.awt.event.KeyEvent evt) {
                    txtIdMembresiaKeyPressed(evt);
                }
            });

            txtNombre.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
            txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
                public void keyPressed(java.awt.event.KeyEvent evt) {
                    txtNombreKeyPressed(evt);
                }
            });

            javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
            jPanel2.setLayout(jPanel2Layout);
            jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(8, 8, 8)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtNombre, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtDescripcion, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(cmbPeriodo, javax.swing.GroupLayout.Alignment.TRAILING, 0, 250, Short.MAX_VALUE)
                                .addComponent(txtPrecio, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtIdMembresia)))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(14, 14, 14)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(70, 70, 70))
            );
            jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(txtIdMembresia, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(44, 44, 44)
                            .addComponent(cmbPeriodo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(47, 47, 47))
            );

            btnSave.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
            btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/agregar-archivo.png"))); // NOI18N
            btnSave.setText("Guardar");
            btnSave.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnSaveActionPerformed(evt);
                }
            });

            btnCancel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
            btnCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/eliminar.png"))); // NOI18N
            btnCancel.setText("Cancelar");
            btnCancel.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnCancelActionPerformed(evt);
                }
            });

            javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
            jPanel1.setLayout(jPanel1Layout);
            jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(167, 167, 167)
                    .addComponent(btnSave, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(btnCancel, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                    .addGap(118, 118, 118))
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(6, 6, 6)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(18, 18, 18))
            );
            jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(27, 27, 27)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                        .addComponent(btnCancel, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                        .addComponent(btnSave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGap(94, 94, 94))
            );

            javax.swing.GroupLayout winRegistroMembresiasLayout = new javax.swing.GroupLayout(winRegistroMembresias.getContentPane());
            winRegistroMembresias.getContentPane().setLayout(winRegistroMembresiasLayout);
            winRegistroMembresiasLayout.setHorizontalGroup(
                winRegistroMembresiasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(winRegistroMembresiasLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );
            winRegistroMembresiasLayout.setVerticalGroup(
                winRegistroMembresiasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            );

            popMnuEditar.setText("Editar");
            popMnuEditar.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    popMnuEditarActionPerformed(evt);
                }
            });
            PopUpmnuMembresia.add(popMnuEditar);

            popMnuEliminar.setText("Eliminar");
            popMnuEliminar.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    popMnuEliminarActionPerformed(evt);
                }
            });
            PopUpmnuMembresia.add(popMnuEliminar);

            popMnuImprimir.setText("Imprimir");
            popMnuImprimir.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    popMnuImprimirActionPerformed(evt);
                }
            });
            PopUpmnuMembresia.add(popMnuImprimir);
            PopUpmnuMembresia.add(jSeparator1);

            popMnuCerrar.setText("Cerrar");
            popMnuCerrar.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    popMnuCerrarActionPerformed(evt);
                }
            });
            PopUpmnuMembresia.add(popMnuCerrar);

            setClosable(true);
            setIconifiable(true);
            setMaximizable(true);
            setResizable(true);
            setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/img/tarjeta-de-membresia.png"))); // NOI18N
            setPreferredSize(new java.awt.Dimension(900, 500));

            jPanel4.setBackground(new java.awt.Color(130, 114, 103));

            lbTotal.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
            lbTotal.setText("Total: ");

            jScrollPane1.setComponentPopupMenu(PopUpmnuMembresia);
            jScrollPane1.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 14)); // NOI18N
            jScrollPane1.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    jScrollPane1MouseClicked(evt);
                }
            });

            tblMembresias.setBackground(new java.awt.Color(189, 175, 145));
            tblMembresias.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
            tblMembresias.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {

                },
                new String [] {
                    "ID Membresia", "Nombre", "Descripcion", "Precio"
                }
            ));
            tblMembresias.setComponentPopupMenu(PopUpmnuMembresia);
            tblMembresias.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    tblMembresiasMouseClicked(evt);
                }
            });
            jScrollPane1.setViewportView(tblMembresias);

            Herramientas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
            Herramientas.setRollover(true);

            btnGuardar.setFont(new java.awt.Font("Microsoft YaHei", 1, 14)); // NOI18N
            btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/member-card.png"))); // NOI18N
            btnGuardar.setText("Guardar");
            btnGuardar.setFocusable(false);
            btnGuardar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
            btnGuardar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
            btnGuardar.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnGuardarActionPerformed(evt);
                }
            });
            Herramientas.add(btnGuardar);

            btnEditar.setFont(new java.awt.Font("Microsoft YaHei", 1, 14)); // NOI18N
            btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/muscle2.png"))); // NOI18N
            btnEditar.setText("Editar");
            btnEditar.setFocusable(false);
            btnEditar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
            btnEditar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
            btnEditar.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnEditarActionPerformed(evt);
                }
            });
            Herramientas.add(btnEditar);

            btnEliminar.setFont(new java.awt.Font("Microsoft YaHei", 1, 14)); // NOI18N
            btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/eliminargym.png"))); // NOI18N
            btnEliminar.setText("Eliminar");
            btnEliminar.setFocusable(false);
            btnEliminar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
            btnEliminar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
            btnEliminar.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnEliminarActionPerformed(evt);
                }
            });
            Herramientas.add(btnEliminar);

            btnImprimir.setFont(new java.awt.Font("Microsoft YaHei", 1, 14)); // NOI18N
            btnImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/impresora.png"))); // NOI18N
            btnImprimir.setText("Imprimir");
            btnImprimir.setFocusable(false);
            btnImprimir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
            btnImprimir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
            btnImprimir.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnImprimirActionPerformed(evt);
                }
            });
            Herramientas.add(btnImprimir);

            btnSalir.setFont(new java.awt.Font("Microsoft YaHei", 1, 14)); // NOI18N
            btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/salida.png"))); // NOI18N
            btnSalir.setText("Salir");
            btnSalir.setFocusable(false);
            btnSalir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
            btnSalir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
            btnSalir.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnSalirActionPerformed(evt);
                }
            });
            Herramientas.add(btnSalir);

            javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
            jPanel4.setLayout(jPanel4Layout);
            jPanel4Layout.setHorizontalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Herramientas, javax.swing.GroupLayout.DEFAULT_SIZE, 894, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 884, Short.MAX_VALUE)
                                .addComponent(lbTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(10, 10, 10)))
                    .addContainerGap())
            );
            jPanel4Layout.setVerticalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(Herramientas, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(31, 31, 31)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                    .addGap(18, 18, 18)
                    .addComponent(lbTotal)
                    .addContainerGap())
            );

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            );

            pack();
        }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        int fila = tblMembresias.getSelectedRow();
        if (fila != -1) {
            int idMembresia = Integer.parseInt(tblMembresias.getValueAt(fila, 0).toString());
            int resp = JOptionPane.showConfirmDialog(rootPane, "Esta seguro que quieres eliminar esta membresia " + idMembresia,
                    "ELiminar", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (resp == JOptionPane.YES_OPTION) {
                gestionMembresias.conectarBD();
                if (gestionMembresias.eliminarMembresia(idMembresia)) {
                    JOptionPane.showMessageDialog(rootPane, "Membresia eliminada", "Eliminar", JOptionPane.INFORMATION_MESSAGE);
                    listarMembresias();
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Error al intentar eliminar", "Eliminar", JOptionPane.INFORMATION_MESSAGE);
                }
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Seleccione la membresia que desea eliminar", "Eliminar", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        winRegistroMembresias.setSize(600, 500);
        winRegistroMembresias.setTitle("Guardar");
        ImageIcon img = new ImageIcon(getClass().getResource("/img/tarjeta-de-membresia.png"));
        winRegistroMembresias.setIconImage(img.getImage());
        limpiar();
        winRegistroMembresias.setLocationRelativeTo(winRegistroMembresias);
        winRegistroMembresias.setVisible(true);
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        int fila = tblMembresias.getSelectedRow();
        if (fila != -1) {
            winRegistroMembresias.setSize(600, 500);
            winRegistroMembresias.setTitle("Editar");
            ImageIcon img = new ImageIcon(getClass().getResource("/img/tarjeta-de-membresia.png"));
            winRegistroMembresias.setIconImage(img.getImage());
            int idMembresia = Integer.parseInt(tblMembresias.getValueAt(fila, 0).toString());
            membresias = gestionMembresias.buscarMembresias(idMembresia);
            txtIdMembresia.setEditable(false);
            txtIdMembresia.setText(String.valueOf(membresias.getIdMembresia()));
            txtNombre.setText(membresias.getNombre());
            txtDescripcion.setText(membresias.getDescripcion());
            cmbPeriodo.setSelectedItem(membresias.getPeriodo());
            txtPrecio.setText(String.valueOf(membresias.getPrecio()));
            winRegistroMembresias.setLocationRelativeTo(winRegistroMembresias);
            winRegistroMembresias.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(rootPane, "Seleccione la fila que desea editar", "editar", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirActionPerformed
        gestionMembresias.cargarReporteMembresias();
    }//GEN-LAST:event_btnImprimirActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        limpiar();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        String msg = validarDatos();
        if (msg.equals("")) {
            membresias = new Membresias();
            membresias.setIdMembresia(Integer.parseInt(txtIdMembresia.getText()));
            membresias.setNombre(txtNombre.getText());
            membresias.setDescripcion(txtDescripcion.getText());
            membresias.setPeriodo(cmbPeriodo.getSelectedItem().toString());
            membresias.setPrecio(Double.parseDouble(txtPrecio.getText()));

            if (winRegistroMembresias.getTitle().equals("Guardar")) {
                if (gestionMembresias.insertarMembresia(membresias)) {
                    JOptionPane.showMessageDialog(winRegistroMembresias, "Membresia almacenada exitosamente", "Guardar", JOptionPane.INFORMATION_MESSAGE);
                    winRegistroMembresias.dispose();
                    listarMembresias();
                } else {
                    JOptionPane.showMessageDialog(winRegistroMembresias, "Error al intentar guardar membresia", "Guardar", JOptionPane.ERROR_MESSAGE);
                }
            }
            if (winRegistroMembresias.getTitle().equals("Editar")) {
                if (gestionMembresias.editarMembresia(membresias)) {
                    JOptionPane.showMessageDialog(winRegistroMembresias, "Membresia editada exitosamente", "Editar", JOptionPane.INFORMATION_MESSAGE);
                    winRegistroMembresias.dispose();
                    listarMembresias();
                } else {
                    JOptionPane.showMessageDialog(winRegistroMembresias, "Error al intentar editar la membresia", "Editar", JOptionPane.ERROR_MESSAGE);
                }

            }
        } else {
            JOptionPane.showMessageDialog(winRegistroMembresias, msg, "Validando datos", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void txtIdMembresiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdMembresiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdMembresiaActionPerformed

    private void popMnuEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_popMnuEditarActionPerformed
        btnEditarActionPerformed(evt);
    }//GEN-LAST:event_popMnuEditarActionPerformed

    private void popMnuEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_popMnuEliminarActionPerformed
        btnEliminarActionPerformed(evt);
    }//GEN-LAST:event_popMnuEliminarActionPerformed

    private void popMnuImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_popMnuImprimirActionPerformed
int fila = tblMembresias.getSelectedRow();
        if (fila != -1) {
            int idMembresia = Integer.parseInt(tblMembresias.getValueAt(fila, 0).toString());
            int resp = JOptionPane.showConfirmDialog(rootPane, "¿Desea imprimir esta membresia: " + idMembresia +"?", "Imprimir", JOptionPane.YES_OPTION);
            if (resp == JOptionPane.YES_OPTION) {
                gestionMembresias.cargarReporteUnaMembresia(idMembresia);
            } else {
                JOptionPane.showMessageDialog(rootPane, "Error al intentar imprimir", "Imprimir", JOptionPane.INFORMATION_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Seleccione la membresia que desea imprimir", "imprimir", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_popMnuImprimirActionPerformed

    private void popMnuCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_popMnuCerrarActionPerformed
        this.dispose();
    }//GEN-LAST:event_popMnuCerrarActionPerformed

    private void jScrollPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane1MouseClicked

    }//GEN-LAST:event_jScrollPane1MouseClicked

    private void tblMembresiasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMembresiasMouseClicked
        if (evt.getClickCount() == 2) { //Al dar doble click
            btnEditarActionPerformed(new ActionEvent(tblMembresias, 0, ""));
        }
    }//GEN-LAST:event_tblMembresiasMouseClicked

    private void txtIdMembresiaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdMembresiaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (txtIdMembresia.getText().trim().equals("")) {
                JOptionPane.showMessageDialog(null, "Por favor ingrese un id");
                txtIdMembresia.requestFocus();

            } else {
                btnSave.doClick();
            }
        }

    }//GEN-LAST:event_txtIdMembresiaKeyPressed

    private void txtNombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (txtNombre.getText().trim().equals("")) {
                JOptionPane.showMessageDialog(null, "Por favor ingrese un nombre");
                txtNombre.requestFocus();

            } else {
                btnSave.doClick();
            }
        }
    }//GEN-LAST:event_txtNombreKeyPressed

    private void txtDescripcionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDescripcionKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (txtDescripcion.getText().trim().equals("")) {
                JOptionPane.showMessageDialog(null, "Por favor ingrese una descripción");
                txtDescripcion.requestFocus();

            } else {
                btnSave.doClick();
            }
        }
    }//GEN-LAST:event_txtDescripcionKeyPressed

    private void txtPrecioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrecioKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (txtPrecio.getText().trim().equals("")) {
                JOptionPane.showMessageDialog(null, "Por favor ingrese un precio");
                txtPrecio.requestFocus();

            } else {
                btnSave.doClick();
            }
        }
    }//GEN-LAST:event_txtPrecioKeyPressed

    private void limpiar() {
        txtIdMembresia.setText("");
        txtNombre.setText("");
        txtDescripcion.setText("");
        cmbPeriodo.setSelectedIndex(0);
        txtPrecio.setText("");

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JToolBar Herramientas;
    public static javax.swing.JPopupMenu PopUpmnuMembresia;
    public static javax.swing.JButton btnCancel;
    public static javax.swing.JButton btnEditar;
    public static javax.swing.JButton btnEliminar;
    public static javax.swing.JButton btnGuardar;
    public static javax.swing.JButton btnImprimir;
    public static javax.swing.JButton btnSalir;
    public static javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> cmbPeriodo;
    public static javax.swing.JLabel jLabel1;
    public static javax.swing.JLabel jLabel2;
    public static javax.swing.JLabel jLabel3;
    public static javax.swing.JLabel jLabel4;
    public static javax.swing.JLabel jLabel5;
    public static javax.swing.JLabel jLabel6;
    public static javax.swing.JPanel jPanel1;
    public static javax.swing.JPanel jPanel2;
    public static javax.swing.JPanel jPanel4;
    public static javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JPopupMenu.Separator jSeparator1;
    public static javax.swing.JLabel lbTotal;
    public static javax.swing.JMenuItem popMnuCerrar;
    public static javax.swing.JMenuItem popMnuEditar;
    public static javax.swing.JMenuItem popMnuEliminar;
    public static javax.swing.JMenuItem popMnuImprimir;
    public static javax.swing.JTable tblMembresias;
    public static javax.swing.JTextField txtDescripcion;
    public static javax.swing.JTextField txtIdMembresia;
    public static javax.swing.JTextField txtNombre;
    public static javax.swing.JTextField txtPrecio;
    public static javax.swing.JDialog winRegistroMembresias;
    // End of variables declaration//GEN-END:variables

    private void listarMembresias() {
        gestionMembresias.conectarBD();
        ResultSet rs = gestionMembresias.listarMembresias();
        if (rs != null) {
            tblMembresias.setModel(gestionMembresias.cargarEnTabla(rs));
            lbTotal.setText("Total: " + tblMembresias.getRowCount());
        }
        gestionMembresias.desconectarBD();
    }

    private String validarDatos() {
        if (txtIdMembresia.getText().trim().equals("")) {
            txtIdMembresia.requestFocus();
            return "Por favor ingrese el id de la membresia";
        } else {
            try {
                Integer.parseInt(txtIdMembresia.getText());
            } catch (NumberFormatException e) {
                txtIdMembresia.requestFocus();
                return "El Id tiene que ser en formato de numero";
            }
        }

        if (txtNombre.getText().trim().equals("")) {
            txtNombre.requestFocus();
            return "Por favor ingrese el nombre de la membresia";
        }

        if (txtDescripcion.getText().trim().equals("")) {
            txtDescripcion.requestFocus();
            return "Por favor ingrese la descripcion de la membresia";
        }

        if (txtPrecio.getText().trim().equals("")) {
            txtPrecio.requestFocus();
            return "Por favor ingrese el precio de la membresia";
        } else {
            try {
                Double.parseDouble(txtPrecio.getText());
            } catch (NumberFormatException e) {
                txtPrecio.requestFocus();
                return "El precio tiene que ser en formato de numero";
            }
        }

        return "";
    }
}
